In [159]:
# import numpy
import numpy as np
from numpy import pi

# Array Creation¶

In [160]:
# 1D
a1D = np.array([1, 2, 3, 4])
a1D

array([1, 2, 3, 4])

In [161]:
# 2D
a2D = np.array([[1, 2], [3, 4]])
a2D

array([[1, 2],
       [3, 4]])

In [162]:
# create complex data
acomplex = np.array([[1, 2], [3, 4]], dtype=complex)
acomplex

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

In [163]:
# full of zeros
zeros = np.zeros((3, 4)) 
zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [164]:
# full of one, can also specify the data type if you want to
ones = np.ones((3, 4), dtype=np.int16)  
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [165]:
# initial content is random and depends on the state of the memory, by default, it is float64
r = np.empty((2, 2))  
r

array([[0., 0.],
       [0., 0.]])

In [166]:
e = np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [167]:
# create numpy array using function
a = np.fromfunction(lambda i, j: i==j, (3,3), dtype=int)
a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [168]:
def f(x, y):
    return x+y

b = np.fromfunction(f, (3,3), dtype=int)
b


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

example 2
np.empty((3, 4))

[[-1.72723371e-077 -1.72723371e-077 -7.90505033e-323  0.00000000e+000]

 [ 2.12199579e-314  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 
 [ 1.75871011e-310  3.50977866e+064  0.00000000e+000  2.17292369e-311]]
 

In [169]:
# create a range of data, returned a array but not list
# np.arange(start, end, step) , start and end are inclusive
a = np.arange(15) 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [170]:
b = np.arange(1, 20, 5)
b

array([ 1,  6, 11, 16])

In [171]:
c = np.arange(0.5, 1, 0.1)  # accept float arguments
c

array([0.5, 0.6, 0.7, 0.8, 0.9])

np.arange sometimes fails to predict the number of elements obtained because of the finite floating point precision

solution : np.linspace(start, end, numberOfElements)

In [172]:
d = np.linspace(0, 20, 5)
d

array([ 0.,  5., 10., 15., 20.])

In [173]:
x = np.linspace(0, 2*pi, 100) # useful to evaluate function at lots of points
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [174]:
f = np.sin(x) # convert the x array's elements' value to sin(value)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

# The basic of numpy array

After creating array, let's look into the detail of the array we create!

In [175]:
a = np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [176]:
# reshape a
a = a.reshape((2,5))

In [177]:
a.shape # (n,m) --> n rows and m columns

(2, 5)

In [178]:
a.ndim # the dimension of a

2

In [179]:
a.size # the total number of elements of the array

10

In [180]:
a.dtype # describing the type of the elements in the array

dtype('float64')

# Basic Operations

## key concept: broadcast
operations on arrays apply elementwise

In [181]:
a = np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
a - 4

array([-3, -2, -1,  0,  1,  2,  3,  4,  5])

In [183]:
a ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [184]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [185]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

## array(matrix) Inner product

In [186]:
A = np.array( [[1,1,1],
              [0,1,1]] )
B = np.array( [[2,0],
              [3,4],
              [5,6]] )

rule for matrix Inner product:

for two matrix in the shape of (a, b) and (c, d):

b = c

and the matrix after inner product is in the shape of (a, d)

In [187]:
A.shape

(2, 3)

In [188]:
B.shape

(3, 2)

In [189]:
C = A.dot(B) # A @ B does the same thing
C

array([[10, 10],
       [ 8, 10]])

In [190]:
C.shape

(2, 2)

For operations like add, mutiply and so on, two matrix must be in the same shape and the elements must be in the same kind.

In [191]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3)) # same shape as a

In [192]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [193]:
b

array([[0.49210641, 0.64469617, 0.88525247],
       [0.68625918, 0.33232054, 0.48699774]])

In [194]:
b += a
b

array([[1.49210641, 1.64469617, 1.88525247],
       [1.68625918, 1.33232054, 1.48699774]])

In [195]:
try:
    a += b
except TypeError as e:
    print(e)
    

Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'


In [196]:
b = np.arange(12).reshape(3,4)

In [197]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
b.sum(axis=0) # sum of each row

array([12, 15, 18, 21])

In [199]:
b.sum(axis=1) # sum of each colunm

array([ 6, 22, 38])

In [200]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [201]:
b.cumsum(axis=0) # cumulative sum along each colunm

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [202]:
b = np.fromfunction(lambda x,y: x**2+y, (5,5), dtype=int)
b

array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [16, 17, 18, 19, 20]])

In [203]:
for i in b:
    print(i)

[0 1 2 3 4]
[1 2 3 4 5]
[4 5 6 7 8]
[ 9 10 11 12 13]
[16 17 18 19 20]


In [205]:
for i in b.flat:
    print(i)

0
1
2
3
4
1
2
3
4
5
4
5
6
7
8
9
10
11
12
13
16
17
18
19
20


In [212]:
a = np.floor(10*np.random.random((3,6)))
a

array([[1., 7., 5., 5., 1., 2.],
       [0., 0., 8., 7., 8., 3.],
       [8., 7., 8., 0., 7., 3.]])

In [213]:
a.ravel() # return the flattened arrray

array([1., 7., 5., 5., 1., 2., 0., 0., 8., 7., 8., 3., 8., 7., 8., 0., 7.,
       3.])

In [214]:
a.T

array([[1., 0., 8.],
       [7., 0., 7.],
       [5., 8., 8.],
       [5., 7., 0.],
       [1., 8., 7.],
       [2., 3., 3.]])